### PR TITLE
Add pypi and conda badges.

### LINKED ISSUE #31: conda recipe for i18nice
Hi @Krutyi-4el,

I have recently switched to `i18nice` from `python-i18n`.
Everything is working fine, thank you for keeping the project alive.

Now, I would like to produce a conda recipe for the project I'm working on: as all the dependencies should be available on a conda channel, I am planning to create a recipe for `i18nice` too.

I am opening this issue to check whether you are ok with that.
Let me know!

Thanks for your attention! :pray:

### PR DESCRIPTION
**Pull request by cmarmo**
`i18nice` recipe has been accepted in the conda-forge conda channel. :tada: 
This pull request adds pypi and conda badges to the readme.

Thanks for considering it.

Closes #31.

### CODE REVIEW

**Comment by Krutyi-4el** [comment]
Thanks for your efforts in making this package available for more users.

The PR itself is fine, but the linked anaconda.org page shows blank description, is that ok?

**Comment by cmarmo** [comment]
I didn't add the optional field "description" in the recipe... my bad.
Some packages have a detailed description, some other just a copy of the summary, some nothing at all.
Would it be ok if I add a basic description in the next release?

**Comment by Krutyi-4el** [comment]
Is it possible to sync the description with the README (like on PyPI)?

**Comment by cmarmo** [comment]
mmmhh ... I can only find text in the yaml field "description", not a link to a file. So, unless I copy the whole readme in the description field (which I don't think is a good idea) I guess this wasn't planned...

**Comment by Krutyi-4el** [comment]
I see. Then you can put something like "See the repository for detailed description" there.

**Review by Krutyi-4el — APPROVED** [review]

**Comment by cmarmo** [comment]
@Krutyi-4el I have updated i18nice on [conda-forge](https://anaconda.org/conda-forge/i18nice) and added a description as previously discussed. I hope this was what you had in mind.

**Comment by Krutyi-4el** [comment]
@cmarmo nice, thank you!

**Pull request merged**
